name: Clojure CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: lein -U deps
    - name: Run tests
      run: lein test

    - name: Deploy
      run: lein deploy
      if: github.ref == 'refs/head/master' || github.ref == 'refs/head/devel'
      env:
        CLOJARS_USERNAME: ${{ secrets.CLOJARS_USERNAME }}
        CLOJARS_PASSWORD: ${{ secrets.CLOJARS_PASSWORD }}
