name: Clojure CI

on:
  push:
    branches:
      - master
      - devel

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: lein -U deps
    - name: Run tests
      run: lein test
    - name: Deploy
      run: lein deploy
